### ISSUE TITLE
Does it provide p2p messaging for users (not things)

### ISSUE THREAD

**Issue by lucasjinreal** [Mainflux/mainflux-lite#1476]
Just like chat app does, provide any Android or iOS client examples? Or maybe flutter?

**Comment by drasko** [comment]
Please go through the documentation at [mainflux.io](https://mainflux.io)

**Comment by lucasjinreal** [comment]
@drasko Thanks. I just notice there is a CLI client for debugging, does there any thirdparty client build upon mainflux? Such as android or iOS?

**Comment by dborovcanin** [comment]
Unfortunately, no. But such contributions (Android or iOS SDKs) are welcome. :)

**Comment by drasko** [comment]
Yes, there are vanilla libraries / clients for MQTT, HTTP, WS and CoAP on Android and others and you can use these. Mainflux let's you use standard clients for messaging.

**Comment by lucasjinreal** [comment]
@drasko @dusanb94 thank u. I found mainflux currently is the best choice for me to implement a product which mainly function are:

1) A customable User struct (i may need more feilds then one in mainflux);
2) User chat peer to peer, and group chat, group creating etc;
3) Users can add friends to each other, and finally everyone will have a Contact book;
4) Every user can have their things (devices), and send commands to their devices.

Does mainflux able to provide all backend functionalities above?

if it does, I'd like build a Flutter client based on mainflux backend

**Comment by drasko** [comment]
@jinfagang

> A customable User struct (i may need more feilds then one in mainflux);
User chat peer to peer, and group chat, group creating etc;

This is OK, Mainflux User struct is flexible, it has `Metadata` substruct field in which you can put whatever you want.

> Users can add friends to each other, and finally everyone will have a Contact book;

This is available now through groups and policies, which have been freshly merged. Please use master branch for your development, where this new feature is available, until we officially release `0.13` which will contain these new features.

> Every user can have their things (devices), and send commands to their devices.

This has been available in Mainflux from the start, by design.

**Comment by lucasjinreal** [comment]
@drasko thank u, i will start build a beautiful flutter client of mainflux, start from register, login, chating for users and grouping chating, then will add things list and control

**Comment by lucasjinreal** [comment]
@drasko btw, does mainflux support send pdf or other files? Or audio message? Does the message struct support these function?

**Comment by drasko** [comment]
@jinfagang yes it does, because Mainflux is content-type agnostic - you can put anything you want into the message. You just need to respect protocol rules (for example MQTT or WS protocol), and use some of the known content-types and formats if you need DB (but you do not need DB for chat, you probably do not need just pub-sub). Please go through the docs and try it out a bit, and you'll figure out how it works.
