### ISSUE TITLE
Consider unifying repetitive code from the PubSub implementations

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1635]
**ENHANCEMENT**
1. Describe the enhancement you are requesting.
Code in different implementations of PubSub is repeated - mostly the code that holds the subscriptions. Consider how we can improve this and prevent code repetition.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
3. This is a should-have.

_Originally posted by @dborovcanin in https://github.com/mainflux/mainflux/pull/1633#pullrequestreview-1063288673_

**Comment by AryanGodara** [comment]
Closing this issue, since the implementation for unification has failed for now.

The three implementations: nats, rabbitmq, and mqtt are very different, and the small parts of repetitive code, where unification may be possible, will need passing of a lot of parameters by reference, and the unified code, needs to have  different implementations for the different types of input parameters received.

So, at this point, the unification doesn't seem like a good idea, as it risks making the code unnecessarily complex.
