### ISSUE TITLE
Mainflux service require permission Write Postgres Database at the first time start service

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1666]
I implement two mainflux platform at two cluster servers for DR/DC architecture. server DC implements Postgres and replicast DC's data to postgres at DR. it requires mode READ ONLY at site DR. We only access to site DR if site DC is down. It requires all of the services of mainflux are ready,  But I can not start some services that connect to Postgres (with mode READ ONLY), I just want to start it to be ready for accessing (NONE OF the ACTION AT SITE DR) when site DC down (mode database at site DR will switched to WRITE when site DC is down). Why some services are require mode write the first time start? is it a bug?

**Comment by dborovcanin** [comment]
Mainflux has nothing to do with how you set up or deploy your DB. However, when connected to the database, Mainflux services will try to execute migrations to put the database in a consistent state. This may cause problems if all the tables (pay attention to **gorp_migrations**) in your read-only instance are out of sync.

**Comment by dborovcanin** [comment]
@ChiQuang98 Any updates, does this comment help you?

**Comment by chombium** [comment]
Hi @ChiQuang98, as @dborovcanin your deployment setup has noting to do with Mainflux.

From what you've written, you want to have active-stand setup, but you've let the services running on both sides. Instead of that you should define of  a failover procedure and tool which will will do the failover automatically when the active node has problems. 

You've started good but there are few things missing:
1. Create two database instances with replications
2. If you want your users to not affected of your changes in the backed you should create a DNS record and switch where does it point to DC or DR based on the active node
3. Define how are you determine if the active is healthy.
4. Install and configure some process (application/Mainflux service) monitoring which will check if the processes which need to run are running and trigger a failover if they cannot be restored
5. The failover would mean that the services which are running on the active nodes are stopped and then start them on the standby node and switch the traffic to it with a DNS record switch or you can add virtual IP on both of the servers.

As you haven't written what kind of setup are you using IaaS or your own configured servers I can't help you more. At the end here are two  videos on how to build HA servers with drbd and heartbeat or pacemaker on GNU/Lunux, so that you can get a feeling of what has to be done:
https://www.youtube.com/watch?v=Nq8K9SPAODc
https://www.youtube.com/watch?v=IxFI0Ms0ULA

**Comment by ChiQuang98** [comment]
Hi @chombium . How About If  I deploy as active - active model. I will have only one cluster NATS and VerneMQ (1 endpoints). the other services will be deployed at both two site. I wonder about service Auth in your architecture, I see N Auth Service and What is the protocol between services Auth? How about if I have two services Auth connect to two Postgres Server [2 Server DB will have the same data because all services (except Auth Service)] will be deployed in two instances (each connecting to a server Postgres Database), What If a request gets a Token to service Auth, which Service will receive the request?
![image](https://user-images.githubusercontent.com/35691187/201250134-7463309e-0aac-4970-ae9f-71c4930db282.png)

**Comment by dborovcanin** [comment]
`What is the protocol between services Auth?` Other services talk to Auth svc via gRPC.
` What If a request gets a Token to service Auth, which Service will receive the request?` Not sure I understand this one. Services use Auth svc gRPC API to pass the desired action, object, and token to it for authorization. The service that sent the request will receive a response. The same goes for messaging. That being said, we are planning to introduce some significant changes before the Mainflux 1.0 release that will affect authorization procedures, including the removal of Mainflux Channels and relying on Mainflux Groups instead.

**Comment by chombium** [comment]
Hi @ChiQuang98,

thanks for the clarification and the nice block diagram. If you want an active-active HA solution I would suggest you build (or buy) Postgres HA cluster which has multiple nodes and is accessible over a load balancer or a proxy. This way all of the PostgreSQL client apps (Mainflux services) will connect to a single database server ip and the ha PostgreSQL server will take care of the rest. One other thing which should be done is to put all of the Mainflux services which are facing the users behind a load balancer or a dns. That way your users won't have to do any changes on how they access Mainflux regardless of which set of services (which server DC/DR) is active. If you use a DNS failover you will define two groups of nodes one is used the other is standby. If there are problems with the active group (you will need some healthchecks), some kind of automation will switch the DNS configuration from the active to the standby group and the standby group will take over. The solution with load balancing means that you will have multiple instances of each service which will serve user requests. The load will be spread across multiple instances and if one fails, the other continue to function and take over the load.

I don't know where are you deploying Mainflux, but if you are doing on some of the public IaaS (Infrastructire as a Service) providers like AWS, GCP, Azure and alike, they all support the above discussed scenarios and you only need to configure what you need.

If you plan to configure everything yourself, it might take you a while depending on the tools which you use.

Here are few videos and links:
https://www.youtube.com/watch?v=J0ErkLo2b1E
https://www.youtube.com/watch?v=qpxKlH7DBjU
https://www.youtube.com/watch?v=o9xU5AcEpjw
https://www.youtube.com/watch?v=Kxpl0ICzQV0

If you are planning to deploy Mainflux on Kubernets, you might want to  take a look at the [devops](https://github.com/mainflux/devops) repo.

**Comment by ChiQuang98** [comment]
thank all for help, I am going to close this issue and try to handling the connection to the Postgres database by Haproxy

**Comment by chombium** [comment]
I would only mention that when choosing you HA setup you should think about the whole maintenance effort and costs of a home  grown solution compared to IaaS provided services as well. Of course all of that depends on where you want to deploy and run the software.
