### ISSUE TITLE
Is thing_key a secret?

### ISSUE THREAD

**Issue by dulataldazharov** [Mainflux/mainflux-lite#1710]
I am a bit confused about the purpose of the thing_key in general. Is it supposed to be a secret? I can see that value is generated the same way for both thing_id and thing_key.
   ```
	if thing.ID == "" {
		id, err := ts.idProvider.ID()
		if err != nil {
			return Thing{}, err
		}
		thing.ID = id
	}

	if thing.Key == "" {
		key, err := ts.idProvider.ID()

		if err != nil {
			return Thing{}, err
		}
		thing.Key = key
	}
   ```
   They both use uuid generation package.
   ```
   func (up *uuidProvider) ID() (string, error) {
	id, err := uuid.NewV4()
	if err != nil {
		return "", errors.Wrap(ErrGeneratingID, err)
	}
	return id.String(), nil
   }
   ```
   If thing_key is indeed meant to be a secret, shouldn't we use some other way of generating it? UUID does not have unpredictability guarantee and is not safe to use as a security data. Also, when using mTLS (as stated in https://docs.mainflux.io/authentication/#mutual-tls-authentication-with-x509-certificates), thing_key is used as a CN (Common Name) which means it is kind of public. Why not use thing_id as a CN instead, doesn't that make much more sense? This makes me very confused about the purpose behind thing keys.

**Comment by arvindh123** [comment]
For mTLS authentication njs script in nginx, it decode the certificate and check the certificate common name equals to MQTT password provided by client for connection   
So only thing_key is present in certificate common name  
https://github.com/mainflux/mainflux/blob/master/docker/ssl/authorization.js#L26-L37

**Comment by dulataldazharov** [comment]
> For mTLS authentication njs script in nginx, it decode the certificate and check the certificate common name equals to MQTT password provided by client for connection So only thing_key is present in certificate common name https://github.com/mainflux/mainflux/blob/master/docker/ssl/authorization.js#L26-L37

Isn't thing_key supposed to be a secret? Why not use thing_id as a common name? Anyone with the public key of a CA can decrypt the certificate and get access to the thing_key.

**Comment by dborovcanin** [comment]
I understand the confusion and many of the decisions have a historical background and are based on use cases and our experience. The story about Mainflux Thing keys goes like this:

Initially, Thing keys were supposed to be secret for obvious reasons. However, in the early days of Mainflux, we decided to have them as plain text and rely on TLS to keep them secret if necessary. The reasons behind these decisions were purely practical and arise from a couple of limitations:
1. Edge devices and sensors have limited resources (CPU power, but also networking bandwidth) and whatever we use has to be simple and short, so JWTs or anything more complex was not an option due to its size and potential overhead for otherwise simple packets.
2. We had to be able to retrieve them because the risk of losing keys was for many use cases unacceptable (for example,  if we stored them securely as passwords and something goes wrong with a remote device, the operator would need to go physically on-site to burn a new key to the device - which is very expensive and time-consuming).

We decided to use Thing keys in a similar way API keys work - they are not as secure as other methods, but they are simple enough and proven good for what we use them.

As for the certificate, your remark is again on point. We could (and probably should) have used Thing ID. However, since we're using mutual TLS, knowing the Thing key does not compromise communication because the client needs to have the private key that corresponds to the certificate in order to establish the connection.

Finally, Thing ID vs Thing key - key you can change, and ID is immutable.

That being said, we consider adding different types of authentication schemas for, say, different types of devices (some edge devices are very powerful nowadays) and potential improvements in form of adding actual API keys and we're already working on significant access control (and architectural) changes that will soon be revealed and included in next release. Suggestions and new ideas are welcome. :)

**Comment by dborovcanin** [comment]
@dulataldazharov Does this answer your questions, can we close the issue?

**Comment by dulataldazharov** [comment]
Apologies! Forgot to respond.
Thank you very much for a very comprehensive answer and prompt response.
Closing the issue.
