### ISSUE TITLE
Postgres reader is not working properly

### ISSUE THREAD

**Issue by ahmmkh** [Mainflux/mainflux-lite#1913]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?
 use postgress reader to get messages
2. What are the expected results?
curl -sSiX GET http://localhost:9009/channels/aecf0902-816d-4e38-a5b3-a1ad9a7cf9e8/messages -H "Authorization: Thing a83b9afb-9022-4f9e-ba3d-4354a08c273a"

HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 05 Apr 2023 16:01:49 GMT
Content-Length: 660

{
    "offset": 0,
    "limit": 10,
    "format": "messages",
    "total": 3,
    "messages": [{
            "channel": "aecf0902-816d-4e38-a5b3-a1ad9a7cf9e8",
            "publisher": "2766ae94-9a08-4418-82ce-3b91cf2ccd3e",
            "protocol": "http",
            "name": "some-base-name:voltage",
            "unit": "V",
            "time": 1276020076.001,
            "value": 120.1
        },
        {
            "channel": "aecf0902-816d-4e38-a5b3-a1ad9a7cf9e8",
            "publisher": "2766ae94-9a08-4418-82ce-3b91cf2ccd3e",
            "protocol": "http",
            "name": "some-base-name:current",
            "unit": "A",
            "time": 1276020072.001,
            "value": 1.3
        },
        {
            "channel": "aecf0902-816d-4e38-a5b3-a1ad9a7cf9e8",
            "publisher": "2766ae94-9a08-4418-82ce-3b91cf2ccd3e",
            "protocol": "http",
            "name": "some-base-name:current",
            "unit": "A",
            "time": 1276020071.001,
            "value": 1.2
        }
    ]
}
3. What are the received results?
{"error":"failed to connect to `host=mainflux-postgres user=mainflux database=messages`: server error (FATAL: database \"messages\" does not exist (SQLSTATE 3D000))","message":"failed to read messages from database"}

4. What are the steps to reproduce the issue?
- create a thing and a channel and send messages there and try to read them through postgres-reader service
5. In what environment did you encounter the issue?
 - dev

7. Additional information you deem important:

**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
   - documentation
   - research
   - tooling

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).

**Comment by ahmmkh** [comment]
i don't know why it's attempting to access a database called messages it's called mainflux with the table messages

**Comment by drasko** [comment]
@ahmmkh as you can see in the config here: https://github.com/mainflux/mainflux/tree/master/readers/postgres#configuration, default DB name is `messages`.

Similarly - our Postgres' writer default DB is `messages`: https://github.com/mainflux/mainflux/tree/master/consumers/writers/postgres#configuration

Both of these are overridden in the `.env` file: https://github.com/mainflux/mainflux/blob/28f4965d26385896bf3067d8f270a5ff84e1a23e/docker/.env#L386, and this value is then used in docker-compose: https://github.com/mainflux/mainflux/blob/28f4965d26385896bf3067d8f270a5ff84e1a23e/docker/addons/postgres-writer/docker-compose.yml#L50

So it looks like your `.env` file is not correct or taken into account, and that your Reader service was deployed without properly set-up `MF_POSTGRES_NAME` var, leading to it using a default value `messages`.

**Comment by ahmmkh** [comment]
my env file indicates MF_POSTGRES_NAME is mainflux 
i'm thinking my docker compose command is somehow not fetching the env correctly . 
that's how i start the services 

docker compose -f docker/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml -f docker/addons/postgres-writer/docker-compose.yml -f docker/addons/postgres-reader/docker-compose.yml --env-file=docker/.env up -d

**Comment by ahmmkh** [comment]
when i access the database manully i find that the writer created a mainflux database normally with messages table where it does have all  the messages i sent

**Comment by ahmmkh** [comment]
![ArcoLinux-2023-10-04-1696440293_screenshot_1920x1080](https://github.com/mainflux/mainflux/assets/17517302/a88725cd-3f7b-4fc0-8a8b-797938ed3eeb)

**Comment by ahmmkh** [comment]
okay i think i got it  in the docker compose of the reader it says MF_POSTGRES_DB_NAME it should be MF_POSTGRES_NAME
@drasko

**Comment by ahmmkh** [comment]
https://github.com/mainflux/mainflux/pull/1914 created a  pull request for it

**Comment by drasko** [comment]
I am not sure, as there are both vars used somewhere.

@dborovcanin @rodneyosodo @arvindh123 please check

**Comment by ahmmkh** [comment]
https://github.com/mainflux/mainflux/blob/28f4965d26385896bf3067d8f270a5ff84e1a23e/internal/clients/postgres/postgres.go#L22C1-L32C2

didn't find any reference in the client code for postgres  to the DB_NAME config variable

**Comment by drasko** [comment]
@ahmmkh indeed, you are right. This looks like a bug, good catch.

@arvindh123 this looks like some of your changes: https://github.com/mainflux/mainflux/blame/28f4965d26385896bf3067d8f270a5ff84e1a23e/docker/addons/postgres-reader/docker-compose.yml#L30, so please take responsibility of reviewing https://github.com/mainflux/mainflux/pull/1914 and guiding it to the resolution.

@ahmmkh can you please just sign your commits, because DCO is failing - you will find the instructions here: https://github.com/mainflux/mainflux/pull/1914/checks?check_run_id=17401923571

**Comment by dborovcanin** [comment]
@ahmmkh You are right and the problem is in env vars that do not match config tags, so it defaults to value set [here](https://github.com/mainflux/mainflux/blob/28f4965d26385896bf3067d8f270a5ff84e1a23e/cmd/postgres-reader/main.go#L70). Updates to config to require name [here](https://github.com/mainflux/mainflux/blob/28f4965d26385896bf3067d8f270a5ff84e1a23e/internal/clients/postgres/postgres.go#L27) are also necessary so we remove the aforementioned line, but that is out of the scope of your PR. Good catch, and thanks for the contribution.

**Comment by drasko** [comment]
@dborovcanin can we please open an issue for this config change as well in order to track it.

**Comment by arvindh123** [comment]
@drasko , 
I will review this PR 
 
I changed these lines while working for gRPC mTLS.   
While working on gRPC mTLS PR, When  I tried to run postgres-reader with command `docker-compose -f docker/addons/postgres-reader/docker-compose.yml --env-file docker/.env  up ` .  
I got following warning log 
`WARN[0000] The "MF_POSTGRES_DB_NAME" variable is not set. Defaulting to a blank string. `

To fix this warning i changed following lines
```diff 
- MF_POSTGRES_DB_NAME: ${MF_POSTGRES_DB_NAME}
+ MF_POSTGRES_DB_NAME: ${MF_POSTGRES_NAME}
```

Since I want to fix only docker-compose warning, So I didn't checked left side variable `MF_POSTGRES_DB_NAME` .
